# Environment variable mappings for node-config
# These environment variables will override values in default.js

server:
  port: PORT
  host: HOST
  environment: NODE_ENV
  transportType: TRANSPORT_TYPE
  serviceMode: MCP_SERVICE

jira:
  url: JIRA_URL
  email: JIRA_EMAIL
  auth:
    apiToken: JIRA_API_TOKEN
    pat: JIRA_PAT
    oauth2:
      clientId: JIRA_OAUTH_CLIENT_ID
      clientSecret: JIRA_OAUTH_CLIENT_SECRET
      accessToken: JIRA_OAUTH_ACCESS_TOKEN
      refreshToken: JIRA_OAUTH_REFRESH_TOKEN
      redirectUri: JIRA_OAUTH_REDIRECT_URI
  maxResults: JIRA_MAX_RESULTS
  defaultProject: JIRA_DEFAULT_PROJECT

confluence:
  url: CONFLUENCE_URL
  email: CONFLUENCE_EMAIL
  auth:
    apiToken: CONFLUENCE_API_TOKEN
    pat: CONFLUENCE_PAT
    oauth2:
      clientId: CONFLUENCE_OAUTH_CLIENT_ID
      clientSecret: CONFLUENCE_OAUTH_CLIENT_SECRET
      accessToken: CONFLUENCE_OAUTH_ACCESS_TOKEN
      refreshToken: CONFLUENCE_OAUTH_REFRESH_TOKEN
      redirectUri: CONFLUENCE_OAUTH_REDIRECT_URI
  maxResults: CONFLUENCE_MAX_RESULTS
  defaultSpace: CONFLUENCE_DEFAULT_SPACE

logger:
  level: LOG_LEVEL
  pretty: LOG_PRETTY

rateLimit:
  windowMs: RATE_LIMIT_WINDOW_MS
  maxRequests: RATE_LIMIT_MAX_REQUESTS

cache:
  ttlSeconds: CACHE_TTL_SECONDS
  maxItems: CACHE_MAX_ITEMS

ssl:
  rejectUnauthorized: NODE_TLS_REJECT_UNAUTHORIZED
  verifyPeer: SSL_VERIFY_PEER

features:
  enabledTools: ENABLED_TOOLS