# Production environment configuration overrides

logger:
  level: warn    # Only warnings and errors in production
  pretty: false  # JSON logs for production monitoring tools

server:
  environment: production
  host: '0.0.0.0'  # Listen on all interfaces in production

rateLimit:
  windowMs: 900000      # 15 minutes
  maxRequests: 50       # Stricter rate limiting in production

cache:
  ttlSeconds: 600       # Longer cache TTL in production (10 minutes)
  maxItems: 5000        # Larger cache size for production

ssl:
  rejectUnauthorized: true  # Always verify SSL in production
  verifyPeer: true