# 1. Issues
#| Method    | URL                             | Description                      |
#| -------- | ------------------------------- | ----------------------------- |
#| `GET`    | `/issue/{issueIdOrKey}`         | Get full issue data |
#| `POST`   | `/issue`                        | Create new issue          |
#| `PUT`    | `/issue/{issueIdOrKey}`         | Update issue fields          |
#| `DELETE` | `/issue/{issueIdOrKey}`         | Delete issue                |
#| `GET`    | `/search`                       | Search issues by JQL            |
#| `POST`   | `/issue/{issueIdOrKey}/comment` | Add comment          |
#| `GET`    | `/issue/{issueIdOrKey}/comment` | Get comment list  |
#

### Get full issue data
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getIssue
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-get
GET {{baseUrl}}/rest/api/2/issue/AITECH-7?expand=changelog
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


### Update issue
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-editIssue
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-put
PUT {{baseUrl}}/rest/api/2/issue/AITECH-4
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

{
  "fields": {
    "summary": "Updated Test Issue - 2025-09-19T18-15",
    "description": "Updated description for API testing 2"
  }
}

### Add worklog
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-addWorklog
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-worklogs/#api-rest-api-2-issue-issueidorkey-worklog-post
POST {{baseUrl}}/rest/api/2/issue/AITECH-1/worklog
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

{
  "timeSpent": "2m",
  "comment": "API test worklog entry",
  "started": "2025-09-19T15:00:00.000+0000"
}

### Get issue link types
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issueLinkType-getIssueLinkTypes
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-link-types/#api-rest-api-2-issuelinktype-get
GET {{baseUrl}}/rest/api/2/issueLinkType
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}
Content-Type: application/json

### Create remote link
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-createOrUpdateRemoteIssueLink
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-remote-links/#api-rest-api-2-issue-issueidorkey-remotelink-post
POST {{baseUrl}}/rest/api/2/issue/AITECH-4/remotelink
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

{
  "object" : {
    "url" : "https://example.com/test-link",
    "title" : "Test Remote Link"
  }
}

### Get remote links
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getRemoteIssueLinks
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-remote-links/#api-rest-api-2-issue-issueidorkey-remotelink-get
GET {{baseUrl}}/rest/api/2/issue/AITECH-4/remotelink
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


### Get issue with links
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getIssue
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-get
GET {{baseUrl}}/rest/api/2/issue/AITECH-4?fields=issuelinks
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}



### Add comment
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-addComment
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-comments/#api-rest-api-2-issue-issueidorkey-comment-post
POST {{baseUrl}}/rest/api/2/issue/AITECH-7/comment
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

{
  "body": "API test comment"
}



### Create issue link
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issueLink-linkIssues
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-links/#api-rest-api-2-issuelink-post
POST {{baseUrl}}/rest/api/2/issueLink
Content-Type: application/json
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

{
  "type": {
    "name": "Clone"
  },
  "inwardIssue": {
    "key": "AITECH-1"
  },
  "outwardIssue": {
    "key": "AITECH-2"
  },
  "comment": {
    "body": "Link created for API testing"
  }
}



### create Issue:
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-createIssue
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-post
POST {{baseUrl}}/rest/api/2/issue
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}
Content-Type: application/json

{
  "fields": {
    "project": {
      "key": "AITECH"
    },
    "summary": "TEST-AITECH-2",
    "issuetype": {
      "name": "Задача+"
    },
    "description": "Three maidens by the window\nSpinning late in the evening",
    "assignee": {
      "name": "vvpupkin"
    },
    "labels": ["CS-BOT"],
    "priority": {
      "id": "10504"
    }
  }
}


### Create issue attachment
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-addAttachment
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-attachments/#api-rest-api-2-issue-issueidorkey-attachments-post
POST {{baseUrl}}/rest/api/2/issue/AITECH-5/attachments
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}
X-Atlassian-Token: no-check
Content-Type: multipart/form-data; boundary=WebAppBoundary
x-on-behalf-of-user: {{SUBST_USER}}
X-Atlassian-Token: no-check

--WebAppBoundary
Content-Disposition: form-data; name="comment"
Content-Type: text/plain

Test upload
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< ./test-attachment.txt
--WebAppBoundary--


###

# 2. Metadata

#| Method | URL                              | Description                                                                         |
#| ----- | -------------------------------- | -------------------------------------------------------------------------------- |
#| `GET` | `/issue/createmeta`              | Metadata for creating issues (project list, issue types, required fields) |
#| `GET` | `/issue/{issueIdOrKey}/editmeta` | Available fields for editing specific issue                              |
#| `GET` | `/priority`                      | Priority list                                                               |
#| `GET` | `/status`                        | All statuses list                                                             |

### Get create metadata
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getCreateIssueMetadata
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-createmeta-get
GET {{baseUrl}}/rest/api/2/issue/createmeta
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Get priorities
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#priority-getPriorities
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-priorities/#api-rest-api-2-priority-get
GET {{baseUrl}}/rest/api/2/priority
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Get edit metadata
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getEditIssueMeta
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-editmeta-get
GET {{baseUrl}}/rest/api/2/issue/AITECH-845/editmeta
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Get statuses
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#status-getStatuses
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-workflow-statuses/#api-rest-api-2-status-get
GET {{baseUrl}}/rest/api/2/status
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

# 3. Projects

#| Method | URL                                  | Description                         |
#| ----- | ------------------------------------ | -------------------------------- |
#| `GET` | `/project`                           | All projects                      |
#| `GET` | `/project/{projectIdOrKey}`          | Project data                   |
#| `GET` | `/project/{projectIdOrKey}/statuses` | Statuses by issue types in project |


### Get all projects
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#project-getAllProjects
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-projects/#api-rest-api-2-project-get
GET {{baseUrl}}/rest/api/2/project
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


### Get project
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#project-getProject
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-projects/#api-rest-api-2-project-projectidorkey-get
GET {{baseUrl}}/rest/api/2/project/AITECH
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


# 4. Transitions

#| Method  | URL                                 | Description                         |
#| ------ | ----------------------------------- | -------------------------------- |
#| `GET`  | `/issue/{issueIdOrKey}/transitions` | Possible issue transitions        |
#| `POST` | `/issue/{issueIdOrKey}/transitions` | Change issue status |

### Issue status change example:
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-doTransition
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-transitions-post
POST {{baseUrl}}/rest/api/2/issue/TEST-1/transitions
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

{
  "transition": { "id": "31" }
}


### Possible issue transitions
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getTransitions
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-transitions-get
GET {{baseUrl}}/rest/api/2/issue/AITECH-5/transitions
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


### Possible issue transitions with params
# https://docs.atlassian.com/software/jira/docs/api/REST/8.13.20/#issue-getTransitions
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-transitions-get
GET {{baseUrl}}/rest/api/2/issue/AITECH-5/transitions?includeUnavailableTransitions=false&skipRemoteOnlyCondition=true
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


###

#5. Users

#| Method  | URL                             | Description                              |
#| ------ | ------------------------------- | ------------------------------------- |
#| `GET`  | `/user?username={name}`         | Find user by name           |
#| `GET`  | `/user/search?username={query}` | Search users                   |
#| `POST` | `/user`                         | Create user (if allowed) |

###
GET {{baseUrl}}/rest/api/2/user?username=vvmakarov
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

###
GET {{baseUrl}}/rest/api/2/user/search?username=Makarov
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


#6. Worklog
#| Method  | URL                             | Description            |
#| ------ | ------------------------------- | ------------------- |
#| `GET`  | `/issue/{issueIdOrKey}/worklog` | All work logs     |
#| `POST` | `/issue/{issueIdOrKey}/worklog` | Add work log |


#7. Attachments
#| Method  | URL                                 | Description                                             |
#| ------ | ----------------------------------- | ---------------------------------------------------- |
#| `POST` | `/issue/{issueIdOrKey}/attachments` | Upload file (requires `X-Atlassian-Token: no-check`) |
#| `GET`  | `/attachment/{id}`                  | Download attachment                                     |
#

# Additional features
# Pagination — startAt and maxResults parameters for /search and other lists.
# Expand — expand parameter for loading nested data (renderedFields, transitions, changelog).
# JQL — powerful issue search language.
# JQL search example:

###
POST {{baseUrl}}/rest/api/2/search

{
  "jql": "project = TEST AND status = 'Open'",
  "maxResults": 50,
  "fields": ["summary", "status", "assignee"]
}



### AUTOMATION

### reporter
GET {{baseUrl}}/rest/api/latest/user/search?username=Makaro
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### labels
GET {{baseUrl}}/rest/api/1.0/labels/suggest?query=CS
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### issuelinks
GET {{baseUrl}}/rest/api/2/issue/picker?currentProjectId=&showSubTaskParent=true&showSubTasks=true&currentIssueKey=AITECH-845&query=CSB
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Watchers
GET {{baseUrl}}/rest/api/1.0/users/picker?fieldName=customfield_26803&query=Makaro
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### assignee
GET {{baseUrl}}/rest/api/latest/user/assignable/search?issueKey=AITECH-845&username=Makaro
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### assignee
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getAllBoards
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-get
GET {{baseUrl}}/rest/agile/1.0/board/
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


### assignee
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getAllSprints
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-sprint-get
GET {{baseUrl}}/rest/agile/1.0/board/968/sprint
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


### assignee
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getAllSprints
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-sprint-get
GET {{baseUrl}}/rest/agile/1.0/board/820/sprint
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Kanban boards list
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getAllBoards
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-get
GET {{baseUrl}}/rest/agile/1.0/board?type=kanban
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board info (EDOX PROD ISSUES board - ID 820)
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getBoard
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-get
GET {{baseUrl}}/rest/agile/1.0/board/820
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board configuration (columns, ranking, estimation)
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getConfiguration
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-configuration-get
GET {{baseUrl}}/rest/agile/1.0/board/820/configuration
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board projects
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getProjects
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-project-get
GET {{baseUrl}}/rest/agile/1.0/board/820/project
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board issues with JQL and quick filter
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getIssuesForBoard
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-issue-get
GET {{baseUrl}}/rest/agile/1.0/board/820/issue?jql=project%20%3D%20AITECH%20AND%20status%20!%3D%20Done&maxResults=50&quickFilterId=1
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board epics
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getEpics
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-epic-get
GET {{baseUrl}}/rest/agile/1.0/board/820/epic
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Issues of a specific epic on the board
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getIssuesForEpic
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-epic-epicid-issue-get
GET {{baseUrl}}/rest/agile/1.0/board/820/epic/12345/issue
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board versions
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getVersions
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-version-get
GET {{baseUrl}}/rest/agile/1.0/board/820/version
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Board properties (list)
# https://docs.atlassian.com/jira-software/REST/8.13.0/#agile/1.0/board-getPropertiesKeys
# https://developer.atlassian.com/server/jira/platform/rest/v11001/api-group-board/#api-agile-1-0-board-boardid-properties-get
GET {{baseUrl}}/rest/agile/1.0/board/820/properties
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

### Create Version
POST {{baseUrl}}/rest/api/2/version
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}

###
GET {{baseUrl}}/rest/api/2/myself
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}
x-on-behalf-of-user: {{SUBST_USER}}

###
GET {{baseUrl}}/rest/api/2/serverInfo
Authorization: Basic {{JIRA_USER}} {{JIRA_PASS}}


